version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: nexoworld_database
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - nexoworld-database-volume:/var/lib/postgresql/data
    networks:
      - nexoworld-network

networks:
  nexoworld-network:
    driver: bridge

volumes:
  nexoworld-database-volume:
    driver: local
